apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE_NAME}-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  OMIE_APP_KEY: "${OMIE_APP_KEY}"
  OMIE_APP_SECRET: "${OMIE_APP_SECRET}"
